name: RSS Scheduler

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  run-rss:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"
          cache: true

      - name: Go env
        run: go env
        env:
          TENCENT_CLOUD_SECRET_ID:  ${{ secrets.TENCENT_CLOUD_SECRET_ID }}
          TENCENT_CLOUD_SECRET_KEY: ${{ secrets.TENCENT_CLOUD_SECRET_KEY }}
          TOKEN:                    ${{ secrets.TOKEN }}
          NAME:                     ${{ secrets.NAME }}
          REPOSITORY:               ${{ secrets.REPOSITORY }}
          COSRSS:                   ${{ secrets.COSURL }}
          DefaultAvatarURL:         ${{ secrets.DEFAULT_AVATAR_URL }}
          COSAvatar:                ${{ secrets.COS_AVATAR }}
          COSFavoriteRSS:           ${{ secrets.COS_MY_FAVORITE_RSS }}
          COSForeverBlog:           ${{ secrets.COS_FOREVER_BLOG }}
          COSNameMapping:           ${{ secrets.COS_NAME_MAPPING  }}
          MAX_RETRIES:              3
          RETRY_INTERVAL:           10s
          MAX_CONCURRENCY:          10
          HTTP_TIMEOUT:             15s

      - name: Install dependencies
        run: go mod tidy

      - name: Build and run
        run: |
          go run ./cmd/main.go

      - name: Show error logs
        if: always()
        run: |
          today=$(date +%Y-%m-%d)
          echo "=== ERROR LOGS for $today ==="
          cat logs/error-$today.log || true

      - name: Show summary logs
        if: always()
        run: |
          today=$(date +%Y-%m-%d)
          echo "=== SUMMARY LOGS for $today ==="
          cat logs/summary-$today.log || true

      - name: Upload logs as artifact
        if: always()
        uses: actions/upload-artifact@v3.1.0
        with:
          name: logs-archive
          path: logs/