name: RSS Scheduler

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  scheduler-rss:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.24'
    
    - name: Install dependencies
      run: |
        go mod tidy
        go mod vendor

    - name: Run go program with debug info
      run: |
        echo "Running go program..."
        go run .
      env:
        TENCENT_CLOUD_SECRET_ID: ${{ secrets.TENCENT_CLOUD_SECRET_ID }}
        TENCENT_CLOUD_SECRET_KEY: ${{ secrets.TENCENT_CLOUD_SECRET_KEY }}
        TOKEN: ${{ secrets.TOKEN }}
        NAME: ${{ secrets.NAME }}
        REPOSITORY: ${{ secrets.REPOSITORY }}
        COSURL: ${{ secrets.COSURL }}
        MAX_RETRIES: 3
        RETRY_INTERVAL: 10s
        MAX_CONCURRENCY: 10
        HTTP_TIMEOUT: 15s
